### ISSUE TITLE
Allow passing username/password for database

### ISSUE THREAD

**Issue by loganr-w** [ngageoint/seed-silo#35]
**Paint Point? Please describe.**
The username and password for my Postgres database are stored in a vault. 

**Desired Solution**
If the passed in parameter for `DATABASE_URL` is a Postgres database, it checks for `DATABASE_USERNAME` and `DATABASE_PASSWORD` and appends it onto the database url string.

**Comment by JohnPTobe** [comment]
So you can't put the username/password into the DATABASE_URL environment variable? You have to get them from a vault?

**Comment by loganr-w** [comment]
An example YAML:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silo-app
  template:
    metadata:
      labels:
        app: silo-app
    spec:
      containers:
      - name: silo-container
        image: repo/seed-silo
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres-service:5432/silo
        - name: SILO_ADMIN
          valueFrom:
            secretKeyRef:
              name: silo-seed-secret
              key: password
        - name: SILO_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: silo-seed-secret
              key: password
        - name: SILO_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: SILO_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
```
